skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_contract = "4y1ViT1Uc7aaj5Kw7bca22DahqbmvSMeMUh6qNVrv7YV"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
