skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_contract = "FYLQ37BMWhdhqDpieatcdrujk9ZVW6GfujxeAhCy4WZv"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
