"""updated service model

Revision ID: 1ad7417a64c8
Revises: ce62615eece1
Create Date: 2026-07-29 10:29:52.735258

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad7417a64c8'
down_revision: Union[str, Sequence[str], None] = 'ce62615eece1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('business_name', sa.String(), nullable=False))
    op.add_column('services', sa.Column('starting_price', sa.Float(), nullable=False))
    op.add_column('services', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.add_column('services', sa.Column('location_name', sa.String(), nullable=False))
    op.drop_column('services', 'max_price')
    op.drop_column('services', 'min_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('min_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('max_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('services', 'location_name')
    op.drop_column('services', 'location')
    op.drop_column('services', 'starting_price')
    op.drop_column('services', 'business_name')
    # ### end Alembic commands ###
