"""add budget to job model

Revision ID: 250b19ddb7b8
Revises: f5088da717a5
Create Date: 2026-07-27 13:12:01.558541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250b19ddb7b8'
down_revision: Union[str, Sequence[str], None] = 'f5088da717a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('budget', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'budget')
    # ### end Alembic commands ###
