"""fixed service model

Revision ID: 7a4116069030
Revises: 1ad7417a64c8
Create Date: 2026-07-29 10:52:24.219180

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4116069030'
down_revision: Union[str, Sequence[str], None] = '1ad7417a64c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.add_column('service_requests', sa.Column('location_name', sa.String(), nullable=False))
    op.alter_column('service_requests', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_requests', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('service_requests', 'location_name')
    op.drop_column('service_requests', 'location')
    # ### end Alembic commands ###
