"""add business media relationship

Revision ID: 7ec44a13ae47
Revises: 8505d048d9ff
Create Date: 2026-08-15 10:06:17.473378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec44a13ae47'
down_revision: Union[str, Sequence[str], None] = '8505d048d9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'near_application_id')
    op.drop_column('jobs', 'near_task_id')
    op.add_column('media', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'business_id')
    op.add_column('jobs', sa.Column('near_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_applications', sa.Column('near_application_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
