"""fixed job model

Revision ID: 8bff32d101ed
Revises: 7a4116069030
Create Date: 2026-08-08 23:58:40.452444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bff32d101ed'
down_revision: Union[str, Sequence[str], None] = '7a4116069030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('client_completed', sa.Boolean(), nullable=False))
    op.add_column('jobs', sa.Column('worker_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'worker_completed')
    op.drop_column('jobs', 'client_completed')
    # ### end Alembic commands ###
