"""add job location fields

Revision ID: be55d1e40670
Revises: cb98dc27a9c3
Create Date: 2026-07-13 11:14:07.024128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'be55d1e40670'
down_revision: Union[str, Sequence[str], None] = 'cb98dc27a9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.add_column('jobs', sa.Column('location_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'location_name')
    op.drop_column('jobs', 'location')
    # ### end Alembic commands ###
