"""update reports model

Revision ID: c3629f3130ba
Revises: 187a51f17077
Create Date: 2026-08-27 16:41:13.624461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3629f3130ba'
down_revision: Union[str, Sequence[str], None] = '187a51f17077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('description', sa.String(length=1000), nullable=True))
    op.create_foreign_key(None, 'reports', 'jobs', ['reported_job_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['reported_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'description')
    # ### end Alembic commands ###
