"""made default status for jobapplication PENDING

Revision ID: cb98dc27a9c3
Revises: 2535e54c92a6
Create Date: 2026-07-11 00:40:01.563503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb98dc27a9c3'
down_revision: Union[str, Sequence[str], None] = '2535e54c92a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
