"""update models: add service and job related tables

Revision ID: f5088da717a5
Revises: 48eba2f6c33f
Create Date: 2026-07-24 12:54:25.721531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5088da717a5'
down_revision: Union[str, Sequence[str], None] = '48eba2f6c33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_service_requests_provider_id'), 'service_requests', ['provider_id'], unique=False)
    op.create_index(op.f('ix_service_requests_requester_id'), 'service_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_service_requests_service_id'), 'service_requests', ['service_id'], unique=False)
    op.drop_constraint(op.f('service_requests_requester_id_fkey'), 'service_requests', type_='foreignkey')
    op.create_foreign_key(None, 'service_requests', 'users', ['requester_id'], ['id'])
    op.add_column('services', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_foreign_key(None, 'services', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_column('services', 'category_id')
    op.drop_constraint(None, 'service_requests', type_='foreignkey')
    op.create_foreign_key(op.f('service_requests_requester_id_fkey'), 'service_requests', 'services', ['requester_id'], ['id'])
    op.drop_index(op.f('ix_service_requests_service_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_requester_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_provider_id'), table_name='service_requests')
    # ### end Alembic commands ###
