"""add businesses and update services

Revision ID: f544e9bab24b
Revises: 8bff32d101ed
Create Date: 2026-08-12 16:02:24.436041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f544e9bab24b'
down_revision: Union[str, Sequence[str], None] = '8bff32d101ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_owner_id'), 'businesses', ['owner_id'], unique=True)
    op.add_column('services', sa.Column('business_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_services_owner_id'), table_name='services')
    op.create_index(op.f('ix_services_business_id'), 'services', ['business_id'], unique=False)
    op.drop_constraint(op.f('services_owner_id_fkey'), 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'businesses', ['business_id'], ['id'])
    op.drop_column('services', 'business_name')
    op.drop_column('services', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('business_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key(op.f('services_owner_id_fkey'), 'services', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_services_business_id'), table_name='services')
    op.create_index(op.f('ix_services_owner_id'), 'services', ['owner_id'], unique=False)
    op.drop_column('services', 'business_id')
    op.drop_index(op.f('ix_businesses_owner_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
